from .poste import Poste
from .race import Race
from .login import Login
from .client import Client
from .personnel import Personnel
from .patient import Patient
from .animal_accepte import Animal_accepte
from .Attribution import Attribution
from .details_reservation import Details_reservation
from .discussion import Discussion
from .nourriture import Nourriture
from .rendez_vous import Rendez_vous
from .reservation import Reservation