# Generated by Django 4.2.1 on 2023-06-29 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 19, 2, 53, 575024)),
        ),
    ]
